use std::fs;

#[test]
fn default_permission_excludes_cleanup() {
    let contents = fs::read_to_string("permissions/default.toml")
        .expect("default permission file should exist");

    assert!(contents.contains(r#""allow-share""#));
    assert!(contents.contains(r#""allow-can-share""#));
    assert!(!contents.contains(r#""allow-cleanup""#));
}

#[test]
fn cleanup_permission_remains_explicitly_available() {
    let contents = fs::read_to_string("permissions/autogenerated/commands/cleanup.toml")
        .expect("cleanup permission file should exist");

    assert!(contents.contains(r#"identifier = "allow-cleanup""#));
    assert!(contents.contains(r#"commands.allow = ["cleanup"]"#));
}
